apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: manoshop
  region: ap-northeast-2
managedNodeGroups:
  - name: spot
    instanceType: m5.large
    desiredCapacity: 3
    spot: true